# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content_plain', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('reminder_date', models.DateTimeField()),
            ],
        ),
    ]
