# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
