# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_note_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
