# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_auto_20170913_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
