# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_auto_20170913_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='alert',
            field=models.BooleanField(default=False),
        ),
    ]
