# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0012_auto_20170915_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Checktext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateField(default=datetime.date(2017, 10, 1)),
        ),
        migrations.AddField(
            model_name='checkcontent',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Checktext'),
        ),
        migrations.AddField(
            model_name='note',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.Checkcontent'),
        ),
    ]
