# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_auto_20171001_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content_plain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
