# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 12:12
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_auto_20171001_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wo', 'Work'), ('hm', 'Home'), ('cl', 'School/College'), ('hb', 'Hobby'), ('ot', 'Others')], max_length=14, null=True),
        ),
    ]
