# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0015_auto_20171001_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkcontent',
            name='text',
        ),
        migrations.RemoveField(
            model_name='note',
            name='checklist',
        ),
        migrations.AddField(
            model_name='checkcontent',
            name='check_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='note.Checktext', to_field='text'),
        ),
        migrations.AddField(
            model_name='checkcontent',
            name='note',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='note.Note'),
        ),
        migrations.AlterField(
            model_name='checktext',
            name='text',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateField(default=datetime.date(2017, 10, 8)),
        ),
    ]
