# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0017_auto_20171008_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkcontent',
            name='check_text',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateField(default=datetime.date(2017, 10, 9)),
        ),
    ]
