# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0018_auto_20171009_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateField(default=datetime.date(2017, 10, 15)),
        ),
    ]
