# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0019_auto_20171015_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Othertags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='othertags', to='note.Note')),
            ],
        ),
    ]
